default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: langana
  password: <%= ENV['LANGANA_POSTGRES_PASSWORD'] %>
  host: localhost
  database: old_langana_development

test:
  <<: *default
  username: langana
  password: <%= ENV['LANGANA_POSTGRES_PASSWORD'] %>
  host: localhost
  database: old_langana_test

production:
  <<: *default
