default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: dillon
  password: griffzonen
  host: localhost
  database: old_langana_development

test:
  <<: *default
  username: dillon
  password: griffzonen
  host: localhost
  database: old_langana_test

production:
  <<: *default
